spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_alaoui
    username: "yassine"
    password: "password"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8089